import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
  console.log("Deploying DecentralizedBank...");

  const DecentralizedBank = await ethers.getContractFactory("DecentralizedBank");
  const bank = await DecentralizedBank.deploy();
  await bank.waitForDeployment();

  const address = await bank.getAddress();
  console.log(`DecentralizedBank deployed to: ${address}`);

  // Fund bank so it can provide loans
  console.log("Funding bank with 0.0001 ETH for initial liquidity...");
  const tx = await bank.fundBank({ value: ethers.parseEther("0.0001") });
  await tx.wait();
  console.log("Bank funded successfully!");

  // Create config file for the frontend
  const frontendLibPath = path.join(__dirname, "../../lib");

  if (!fs.existsSync(frontendLibPath)) {
    fs.mkdirSync(frontendLibPath, { recursive: true });
  }

  // Get the artifact (ABI)
  const artifactPath = path.join(__dirname, "../artifacts/contracts/DecentralizedBank.sol/DecentralizedBank.json");
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));

  const configContent = `// Automatically generated by Hardhat deploy script
export const contractAddress = "${address}";
export const contractAbi = ${JSON.stringify(artifact.abi, null, 2)};
`;

  fs.writeFileSync(path.join(frontendLibPath, "contract-config.ts"), configContent);
  console.log("Written contract-config.ts to frontend/lib");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
